### PR TITLE
Allow string title

### PR DESCRIPTION
**Pull request by vezaynk**
As noted in #5

### CODE REVIEW

**Review by IanVS — COMMENTED** [review]
Thanks, this seems reasonable to me.  Would you mind adding a test and updating the README, as well?

**Comment by vezaynk** [comment]
Will do! I've been really busy, but I will get around to it.

**Comment by vezaynk** [comment]
@IanVS I added tests and added in a small refactor to decouple `react-title` from `document.title` (still leaving it as the default). 

Let me know what you think.

**Comment by IanVS** [comment]
Thanks, it seems like this PR is now doing a few different things. Can you explain why you decoupled from setting the title?  And maybe pull that to a separate PR so we can review / discuss it separately?

**Comment by vezaynk** [comment]
Okay I'll roll back my changes and split them into a few PRs

**Comment by IanVS** [comment]
Thanks!  That will make them easier to review/discuss/merge.

**Comment by vezaynk** [comment]
@IanVS ready for reviewing btw

**Pull request closed without merging**
