### PR TITLE
Modernize (typescript, hooks, vite, vitest, @testing-library)

### PR DESCRIPTION
**Pull request by IanVS**
I found that this package is pretty useful, but I wanted to use it in my typescript + react-hooks based project and preferred not to have a class-based component dependency (and also wanted to avoid prop-types as a dependency, even though maybe it gets tree-shaken out).  It was small enough that I rewrote it for myself, and figured I might as well submit a PR in case you're interested in updating some of the dependencies.

I'll understand if you don't want to merge, since there's a lot of changes here.  But, on the other hand, you might like them!  :)

### CODE REVIEW

**Review by tajo — APPROVED** [review]

**Comment by tajo** [comment]
Nice @IanVS! Happy to give you admin for github/npm if you like to.

**Comment by IanVS** [comment]
Sure, that'd be great, thanks!

**Comment by tajo** [comment]
Thanks. Feel free to merge & publish this or any updates. I don't use this lib in any of my projects right now but happy to see it being useful to someone.

**Comment by cherewaty** [comment]
Any plans to publish a new release with these changes to `npm`?

**Comment by IanVS** [comment]
Thanks for the nudge, @cherewaty.  I've released `1.1.0-beta.0`. Mind trying it out to make sure I didn't accidentally break anything, before I publish it to `latest`?

**Comment by cherewaty** [comment]
We've been successfully using `1.1.0-beta.0` for a few weeks :+1:

**Comment by IanVS** [comment]
Thanks for the report.  I've promoted it to `1.1.0` now.  Ugh, I just realized this was a breaking change, since I'm using hooks now, and previous support was for react 16.3+.  I'm going to release `1.1.1` that reverts the changes in this PR, and then will release 2.0 soon.

**Comment by IanVS** [comment]
@tajo do you mind turning on releases in this github repo, so I can use that as a changelog?

**Comment by vezaynk** [comment]
@IanVS Any updates? Just discovered the lib. Very excited to work with it without writing my own TypeScript types.

**Pull request merged**
