### PR TITLE
Remove oldest version for GitHub Actions

### PR DESCRIPTION
**Pull request by vezaynk**
To make CI pass :)

### CODE REVIEW

**Comment by IanVS** [comment]
I don't think we should remove tests for a version we support just to make CI pass.  Can you tell why it's failing?

**Comment by vezaynk** [comment]
@IanVS I explained what's going on in the previous CR. The old way of rendering to the DOM is deprecated, we can't target both versions in the tests. I think its better to target the new one.

The _only_ difference between 16.8 and ^16.8 that affects us (aside from non-breaking changes) is the backporting of the new rendering API. This does _not_ affect the built packages, which will keep working with older versions.

Maintaining compatibility of our tests with 16.8 is not worth it from my perspective and if anything passes ^16.8 but fails 16.8 it is a bug in React, not react-titled.

**Comment by vezaynk** [comment]
There might be a way to run two parallel test setups, with two different versions of @testing-library/react, and so forth. I don't think it's worth the complexity involved and I'm personally not interested in figuring it out. I'm merely hoping to fix the failing CI right now so that a functional CI setup is in place.

If there is interest in a more complex testing setup, that's something to look at later.

**Comment by IanVS** [comment]
OK thanks.  I'll take a look at this soon.  Thanks again for all the work here.

**Comment by IanVS** [comment]
I updated https://github.com/tajo/react-titled/pull/12 to deal with the multiple versions

**Pull request closed without merging**
